name: loan
channels:
  - defaults
  - conda-forge
dependencies:
  # The python interpreter version.
  # Currently Azure ML Workbench only supports 3.5.2 and later.
  - python=3.8.10
  - pip>=20.0.2
  - numpy>=1.22.3
  - pandas==1.4.2
  - pytest>=7.1.2
  - pip:
      - azureml-sdk==1.40.0
      - black>=22.3.0
      - cached-property==1.5.1
      - jsonlines>=3.0.0
      - nteract-scrapbook>=0.4.2
      - pydocumentdb>=2.3.5
      - tqdm==4.64.0
      - pyemd==0.5.1
      - ipywebrtc==0.6.0
      - pre-commit>=2.18.1
      - scipy
      - scikit-learn==1.0.2
      - requests==2.27.1
      - requests-oauthlib==1.3.1
      - regex==2022.3.15
      - seaborn
      - joblib

